export const catBreeds = [
  'Persian',
  'Maine Coon',
  'Siamese',
  'Ragdoll',
  'British Shorthair',
  'Sphynx',
  'Bengal',
  'Scottish Fold',
  'Abyssinian',
  'Birman',
  'Oriental Shorthair',
  'American Shorthair',
  'Devon Rex',
  'Russian Blue',
  'Norwegian Forest Cat',
  'Savannah',
  'Turkish Angora',
  'Himalayan',
  'Chartreux',
  'Tonkinese',
  'Manx',
  'Balinese',
  'Selkirk Rex',
  'Egyptian Mau',
  'Cornish Rex',
] as const;
